#ifndef LDSO_LDSO_GTEST_LIBS_DLOPEN_INIT_FINALIZE_H
#define LDSO_LDSO_GTEST_LIBS_DLOPEN_INIT_FINALIZE_H

void DlopenInitFinalize1();
void DlopenInitFinalize2();

#endif // LDSO_LDSO_GTEST_LIBS_DLOPEN_INIT_FINALIZE_H
